apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vf1mcok7e-python
  janus-idp.io/tekton: vf1mcok7e-python
  backstage.io/kubernetes-id: vf1mcok7e-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vf1mcok7e-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
